### ISSUE TITLE
Wrong type definition for price_based_shipping_rates and weight_based_shipping_rates of the ShippingZone REST resource

### ISSUE THREAD

**Issue by dhalai** [Shopify/shopify-api-ruby#1099]
# Issue summary

Starting from the `shopify-api-ruby` 10.0.0 if the REST API is used there is no way to get weight or price-based shipping rates related to the particular ShippingZone resource.

- `shopify_api` version: 10.0.0 and up

## Expected behavior

The `price_based_shipping_rates` and `weight_based_shipping_rates` attributes of the ShippingZone REST resource should return an array of hashes or an empty array if there are no related rates.

It should work for all API versions. 

## Actual behavior

It returns the TypeError Exception

```
TypeError Exception: Return value: Expected type T.nilable(T::Hash[T.untyped, T.untyped]), got type Array with value [{...}]...
```

## Steps to reproduce the problem

1. Get an existing ShippingZone by using REST API
2. Try to access its `price_based_shipping_rates` or `weight_based_shipping_rates attribute`

**Comment by kliton661** [comment]
0

**Comment by cgarciavega** [comment]
Hi all! any update with this issue? I'm stuck with the same exception

**Comment by nelsonwittwer** [comment]
Thanks for your patience with this! I've tracked down the root problem and we are working on a fix! Unfortunately, the problem seems to be a type misunderstanding upstream with our API at Shopify so I'm not in complete control of the fix. I see this root issue affecting several other issues within our REST resources here which is a bummer :( 

As a workaround, you could use the [rest client directly](https://github.com/Shopify/shopify-api-ruby/blob/main/lib/shopify_api/clients/rest/admin.rb) directly, though you'll have to parse the response accordingly.
