### ISSUE TITLE
ShopifyAPI::Errors::InvalidWebhookError: Invalid webhook HMAC.

### ISSUE THREAD

**Issue by Halvanhelv** [Shopify/shopify-api-ruby#1266]
# Issue summary

- `shopify_api` version: 13.3.1
- Ruby version: 3.22 
- Operating system: macOS Sonoma 14.1.1
- Api version 2023-10

## Expected behavior

Shopify sends me a Webhook I want to make sure Shopify actually sent it to me.  

I'm using 

```
ShopifyAPI::Webhooks::Registry.process(
      ShopifyAPI::Webhooks::Request.new(raw_body: request.raw_post, headers: request.headers.to_h)
    )
```

and make sure the webhook is real.

## Actual behavior

I'm getting an error  `ShopifyAPI::Errors::InvalidWebhookError: Invalid webhook HMAC.`

I have the correct credentials so I can send other requests but I can’t check the webhook

**Comment by lizkenyon** [comment]
Hi there 👋 

Did you use the API to create the webhook subscription? Or did you create the webhook subscription in the Shopify Admin?

If you created the webhooks subscription within the Shopify Admin UI, it is expected to get the Invalid webhook HMAC. This is because the webhook will be signed with the key that is shown in the Admin UI, not your Apps key. 

For your app to consume webook events you will need to create the webhook subscription with the API using the same API key as the one that will be consuming events.

**Comment by Halvanhelv** [comment]
I've come to understand that `ShopifyAPI::Webhooks::Registry.add_registration` is used for setting up handlers in my application for different webhook topics, but it doesn't actually create webhooks on Shopify. To create webhooks, a separate API call to Shopify is required, either via GraphQL or REST API, where I specify the webhook details like topic and endpoint. In my controller, the key step is to include a validity check for incoming webhooks, which also triggers the appropriate handler. This means I don't need to write any additional logic in the controller beyond this verification step. Once the webhook's authenticity is confirmed, `ShopifyAPI::Webhooks::Registry.process` takes over and the handler I've set up manages the specifics of the webhook's data


Did I draw the right conclusions?
