### ISSUE TITLE
ShopifyApi::Session.setup is not a thread safe

### ISSUE THREAD

**Issue by dgtv** [Shopify/shopify-api-ruby#529]
Hi!
We have more than one application and want to operate with them with your gem from Sidekiq workers that use threads. But we found that gem’s configuration is stored inside class attributes which are not thread safe (api_key and secret). Are our concerns right and how could it be fixed?

**Comment by nwtn** [comment]
I think your concerns could be right. Could you provide us with some more detail around your setup and any side effects/problems you’re seeing so we can attempt to reproduce?

Also, if you have a solution in mind, we’re definitely open to a pull request :)

**Comment by dgtv** [comment]
Consider you have have at least 2 partner apps, so you have 2 pairs of `api_key` & `secret` for them.
And a worker that knows a context and setup right credentials for the app with `ShopifyAPI::Session.setup` method:
```ruby
class DemoWorker
  include Sidekiq::Worker

  def perform(id)
    ShopifyAPI::Session.setup(api_key: id, secret: id)
    log_setup(id)
    sleep 10
    log_setup(id)
  end

  def log_setup(id)
    puts 'id: %s, api_key: %s, secret: %s' % [
      id,
      ShopifyAPI::Session.api_key,
      ShopifyAPI::Session.secret
    ]
  end
end
```
Run Sidekiq (by default, one sidekiq process creates 10 threads): `bundle exec sidekiq`
And then by launching workers: `2.times {|id| DemoWorker.perform_async(id) }`
I'm getting next result:
```
id: 0, api_key: 0, secret: 0
id: 1, api_key: 1, secret: 1
id: 0, api_key: 1, secret: 1 # Oh no! 🙀 
id: 1, api_key: 1, secret: 1
```

**Comment by milep** [comment]
We ran into this also, maybe add notification to README that this gem is not threadsafe. There is a note about ActiveResource threadsafety, which kind of implies this gem would be threadsafe. Anyone working on a fix yet?

**Comment by keiya** [comment]
Any updates?

According to `docs/index.md`, ActiveResource is now thread safe.
Is this issue resolved?

https://github.com/Shopify/shopify_api/blob/master/docs/index.md#thread-safety

**Comment by fmichaut-diff** [comment]
Same here, using `9.5.1`. We have an app connected to multiples shopify shops, and we use sidekiq for job scheduling. 

When multiple threads need to request shopify API, they often mess up the other threads sessions. 
If a thread exit his block before the other one has send requests to shopify, the first thread will call `clear_session` effectively stripping the session for the other thread which will simply fail to connect to shopify.

Since we are connecting to multiple shops, there is also the issue where a thread setup a session with shop A, and then another thread goes on and change the session to shop B. Then the first thread will make requests to the wrong shop.

Maybe leveraging `Thread.current` could help fixing the issue ?

**Comment by will-in-wi** [comment]
After writing this, I realized that active resource has been removed as of version 10 of this gem. So this issue might be resolved. I’ll need to test.

**Comment by fedxgibson** [comment]
@will-in-wi Hi Will! 

Do you have any update about using this API with multiple stores? Is it thread safe now? 

Appreciate it :)

**Comment by will-in-wi** [comment]
I'm fairly sure it is, as of the most recent versions. The reason it wasn't before was due to ActiveResource, which isn't part of this Gem anymore.
