### ISSUE TITLE
Errno::ECONNRESET: Connection reset by peer - SSL_connect error

### ISSUE THREAD

**Issue by damienlethiec** [Shopify/shopify-api-ruby#772]
Hi there,

I use the shopify api in a private app and have an weird error: `Errno::ECONNRESET: Connection reset by peer - SSL_connect error`

The error is triggered at this exact moment and only happens once or twice a week :
```
 @shop.with_shopify_session do
      @location_id = ShopifyAPI::Location.first.id
 end
```

Any idea of the reason ? I use automated certificate on Heroku, could there be a link ?

My versions:
    shopify_api (9.2.0)
    shopify_app (14.0.0)
    rails (6.0.3.2)

Thanks a ton in advance

**Comment by tanema** [comment]
I believe this is quite common with SSL connections and should be expected every now and then. How often do you get this error?

**Comment by paulomarg** [comment]
Hey, thanks for reporting this! That error could indeed be related to a certificate, though in this case it could be coming from our side of things rather than from Heroku. The fact that it only happens occasionally is a bit strange, though.

Since this is likely a difficult issue to reproduce, it would be very helpful if we could gather some information

**Comment by paulomarg** [comment]
Apologies, I clicked on the close button by mistake. Reopening the issue.

**Comment by damienlethiec** [comment]
More or less once every 2 days

**Comment by damienlethiec** [comment]
> Apologies, I clicked on the close button by mistake. Reopening the issue.

No problem ;)
