### ISSUE TITLE
Unclear behaviour when updating an email address for an order

### ISSUE THREAD

**Issue by andyw8** [Shopify/shopify-api-ruby#811]
See #810 - I think we may need a documentation update or a change to the library behaviour.

**Comment by skillmatic-co** [comment]
@andyw8 anything? I've got emails going to the wrong people in my app due to this issue.

**Comment by skillmatic-co** [comment]
@andyw8 this too, is still a dagger in my application.

**Comment by skillmatic-co** [comment]
@andyw8 this is still a huge bug in my app.

**Comment by andyw8** [comment]
Hi @skillmatic-co

Thank you for reporting this problem. We are unable to investigate currently, but we will keep this issue open for other users to report if they experience the same problem, and use this information to help prioritize a fix.

You can also ask for help in the [Shopify Developer forums](https://community.shopify.com/c/shopify-apis-and-sdks/bd-p/shopify-apis-and-technology) and refer to the [API Reference Docs](https://shopify.dev/api).

**Comment by skillmatic-co** [comment]
Hi @paulomarg, thanks for investigating. Unfortunately updating the customer's email isn't what I'm trying to do. Please keep me updated on progress here. Thank you!

**Comment by skillmatic-co** [comment]
@paulomarg any update here?

**Comment by skillmatic-co** [comment]
Anyone? Anything?

**Comment by alanhill** [comment]
There seems to be a couple things at play here:

 - `order.customer.email` always takes precedence over `order.email`, this is why the `order.customer.email = nil` hack works
 - when you are making your second request (not sure if you are just calling `.save` or trying to perform some other operation when you get the `orders/updated` webhook), the gem sends the entire order payload on each request, meaning that if your second request isn't doing `order.customer.email = nil` then the customer payload is being sent with the request, and the precedence kicks in, which is why it ends up getting reverted

We'll look into _why_ `order.customer.email` always takes precedence over `order.email` but I don't have a timeline for a fix.

**Comment by skillmatic-co** [comment]
Hi @alanhill,

Thanks so much for chiming in and clarifying. This really helps. I'll go through my code and make sure anywhere I'm updating/saving/modifying the Order I'm applying this hack.
