### ISSUE TITLE
Lack of method credit_left  (also known as available_calls) or its analogues in version 10. *. *

### ISSUE THREAD

**Issue by yevhenii-dolmatov-moc** [Shopify/shopify-api-ruby#971]
# Issue summary
I am trying to update the shopify_api gem version from 9.5.1 to 10.1.0.
But I had a problem using the `available_calls` method (also known as `credit_left`), which was present in the version 9.5.1.

## Expected behavior
Examining the changes in the gem code, I found that this method, along with its module, was removed.
So my question is whether this method was implemented in the new version of the library and what is it called now if it is present?

Thanks and best regards

## Actual behavior
What actually happens?
Lack of credit_left (available_calls) method or its analogues in version 10.

## Specifications

- `shopify_api` version: 10.1.0
- Shopify API version used (example: `2022-04`):

**Comment by omarlatief** [comment]
I'm also curious if there's a workaround here since we rely on this a lot in a few of our apps to make sure we're staying below the rate limits. I've tried searching for the header string "X-Shopify-Shop-Api-Call-Limit" in the code repo with no luck. It's really frustrating that Shopify completely removed this from their gem for no apparent reason.

**Comment by EmmaB** [comment]
Not stale. Nothing about these breaking changes is fixed.

**Comment by mrpunkin** [comment]
It's bad form to move from providing a means for checking available credits in versions prior to 10.0 to a new system in which you have to catch an exception everywhere in your code that might run into rate limits. I can understand not maintaining a module full of methods, but what about caching the latest response headers after each request somewhere like on the ShopifyAPI::Context.active_session object? Even if it were just the `x-shopify-shop-api-call-limit` and `retry-after` headers.

That data is available if you manually build requests, however I'm going to guess most folks using this gem, especially in the context when used alongside the shopify_app gem, are using REST objects and have no means to check those headers currently. You built in storing the pagination metadata, could we get something similar for call limits please?

**Comment by mrpunkin** [comment]
I actually ended up just deciding that instead of monkey patching anything it would be best to just count the cost of each block of code I write and estimate the amount of time I'll need to sleep between iterations of a loop. Almost every one of my sleep calls now is just a static number estimated from the amount of calls I've made in that block.
